version: "2"
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/geoberle)
        - blank
        - dot
